### ISSUE TITLE
workingWithArray

### ISSUE THREAD

**Issue by DanerSound** [DanerSound/ProgettoArchitetture-1819#14]
fare un programma che letto un array dalla memoria  applichi agli elementi di indice pari : STAMPA 

ripeti la stessa operazione con gli elemento di indice dispari

**Comment by DanerSound** [comment]
CORE OPERTATION OF ALGORITMO B  e ALGORITMO C

**Comment by Wabri** [comment]
Perchè hai suddiviso i 2 compiti se è necessario applicare la stessa operazione?

**Comment by DanerSound** [comment]
Per ricordarmi che servono per algoritmi diversi ? Oppure per si sia una scrittura ambigua ?

**Comment by Wabri** [comment]
Me lo chiedi a me?

**Comment by Wabri** [comment]
Io l'ho capito che hai bisogno dello stesso algoritmo per entrambi e mi chiedevo infatti perchè li hai suddivisi

**Comment by DanerSound** [comment]
One word : pio
