### ISSUE TITLE
ALGORITMO-A

### ISSUE THREAD

**Issue by DanerSound** [DanerSound/ProgettoArchitetture-1819#15]
- [x] riprendere la "core operation e provare a decriptare"
- [x] prendere la lettere leggendola da un file e scrivendola su un file
- [x] ripete l'operazione iterando su una stringa

**Comment by DanerSound** [comment]
CORE OPERATION OF ALGORTIMO A

**Comment by Wabri** [comment]
Bello questo algoritmo
